rm(list = ls())
library(DeliveryMan)
source("carmove.R")
source("appendSorted.R")
source("manhattanDist.R")
source("aStar.R")
options(error=traceback)

#runDeliveryMan(carReady = carmove)
testDM(myFunction = carmove)
